/**
 * @fileoverview Text copy dictionary for the SuperAdmin module in Heart Check PHC.
 *
 * Centralizes all user-facing labels, table headers, form placeholders,
 * validation errors, success messages, and dialog confirmations.
 *
 * @module app/superadmin/constants/superadminTexts
 */

export const SUPERADMIN_TEXTS = {
  header: {
    portalTitle: 'SuperAdmin Portal',
    portalSubtitle: 'Philippine Heart Center Queue Management System',
    pageTitle: 'User Accounts & Access',
    pageDescription: 'Manage hospital staff credentials, clinical cubicle authorizations, and triage desk assignments.',
    settingsTitle: 'System Settings & Security',
    settingsDescription: 'Configure global queue automation parameters, session timeouts, and administrator security.',
    addUserButton: 'Add New User',
  },
  navigation: {
    usersTab: 'User Accounts',
    settingsTab: 'System Settings',
    facilitiesLink: 'Facilities & Cubicles',
    customizationLink: 'Kiosk Services',
    signOut: 'Sign Out',
    superadminRoleBadge: 'Super Administrator',
    themeToggleLight: 'Switch to light mode',
    themeToggleDark: 'Switch to dark mode',
    groupAccess: 'Access & Identity',
    navStaffAccounts: 'Staff Accounts',
    groupFacilities: 'Clinical Infrastructure',
    navRooms: 'Rooms & Cubicles',
    navCounters: 'Counter Stations',
    groupKiosk: 'Patient Touchscreen',
    navKioskServices: 'Kiosk Services',
    groupGovernance: 'System & Governance',
    navAutomation: 'Queue Automation',
    navSecurity: 'Administrator Security',
    systemStatus: 'System Operational',
    systemFooter: 'PHC Information Management',
    toggleSidebar: 'Toggle navigation sidebar',
    portalBrand: 'Philippine Heart Center',
    portalSub: 'SuperAdmin Console',
  },
  stats: {
    totalUsersTitle: 'Total Accounts',
    totalUsersDesc: 'All registered hospital users',
    clinicalTitle: 'Clinical Staff',
    clinicalDesc: 'Nurses and attending physicians',
    registrationTitle: 'Registration Officers',
    registrationDesc: 'Front-desk intake staff',
    adminsTitle: 'System Administrators',
    adminsDesc: 'Privileged IT and supervisory roles',
  },
  table: {
    searchPlaceholder: 'Search by email, username, or role...',
    allRoles: 'All Roles',
    filterLabel: 'Filter by role:',
    colEmail: 'Email Address',
    colUsername: 'Username',
    colRole: 'Role',
    colCreated: 'Date Created',
    colActions: 'Actions',
    emptyTitle: 'No users found',
    emptyDesc: 'Try adjusting your search query or role filter.',
    editButton: 'Edit',
    deleteButton: 'Delete',
    loadingUsers: 'Loading staff accounts...',
    pageText: 'Page',
    ofText: 'of',
    prevButton: 'Previous',
    nextButton: 'Next',
    showingText: 'Showing',
    toText: 'to',
    resultsText: 'users',
  },
  modal: {
    addTitle: 'Add New Staff Account',
    editTitle: 'Edit Staff Account',
    addSubtitle: 'Create a new user account with role-based access and desk assignments.',
    editSubtitle: 'Update credentials and fine-tune operational desk assignments.',
    emailLabel: 'Email Address',
    emailPlaceholder: 'staff.name@phc.gov.ph',
    usernameLabel: 'Username / Staff ID',
    usernamePlaceholder: 'e.g. nurse_maria or dr_santos',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter a strong temporary password (min 8 chars)',
    passwordEditHint: 'Leave blank to preserve existing password.',
    roleLabel: 'System Role',
    roleRegistration: 'Registration (Front Desk)',
    roleNurse: 'Nurse (Clinical Station)',
    roleDoctor: 'Doctor (Consultation Cubicle)',
    roleAdmin: 'Administrator (Operations & Reports)',
    roleSuperadmin: 'Super Administrator (Full System Access)',
    clinicalSectionTitle: 'Assigned Clinical Cubicles',
    clinicalSectionDesc: 'Select the cubicles this clinical user is authorized to manage and call patients into.',
    clinicalSelectedBadge: 'selected',
    clinicalRoomPrefix: 'Room',
    registrationSectionTitle: 'Registration Desk & Service Scope',
    registrationSectionDesc: 'Configure which services, consultation rooms, and physical counters this officer handles.',
    assignedServicesLabel: 'Assigned Kiosk Services',
    assignedRoomsLabel: 'Assigned Consultation Rooms',
    assignedRoomsHint: 'Select one or more services above to populate available rooms.',
    assignedCountersLabel: 'Assigned Registration Counters',
    assignedCountersHint: 'Select physical queue counter stations (1 to 5) assigned to this intake officer.',
    cancelButton: 'Cancel',
    saveButton: 'Save Changes',
    createButton: 'Create Account',
    savingButton: 'Saving...',
  },
  deleteModal: {
    title: 'Confirm Account Deletion',
    warning: 'Are you sure you want to permanently delete this user account?',
    dangerNote: 'This action cannot be undone. The user will immediately lose access to all Heart Check PHC systems.',
    confirmButton: 'Delete Account',
    cancelButton: 'Cancel',
    deletingButton: 'Deleting...',
  },
  notifications: {
    userCreated: 'Account created successfully.',
    userUpdated: 'Account updated successfully.',
    userDeleted: 'Account deleted successfully.',
    validationError: 'Please fill in all required fields.',
    emailInvalid: 'Please enter a valid email address.',
    passwordLength: 'Password must be at least 8 characters long.',
  },
} as const;
