/**
 * @fileoverview Style tokens and Tailwind class definitions for the Admin Dashboard
 * Export Data module.
 *
 * Implements high-contrast solid surfaces, enterprise clinical borders, responsive
 * grid layouts, interactive date chip states, and preview surfaces strictly conforming to AGENTS.md.
 *
 * @remarks
 * Zero glassmorphism or milky blurs. High-contrast clinical ergonomics for medical workstations.
 *
 * @module app/dashboard/pages/export/constants/exportStyles
 */

export const EXPORT_STYLES = {
  page: 'space-y-6 pb-12',
  header: {
    root: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    topRow: 'flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between',
    titleBlock: 'space-y-1',
    breadcrumb: 'text-xs font-semibold tracking-wide uppercase text-slate-500 dark:text-slate-400',
    title: 'text-2xl font-bold tracking-tight text-slate-900 dark:text-white',
    subtitle: 'text-sm text-slate-600 dark:text-slate-400 max-w-3xl leading-relaxed',
    actionButtons: 'flex flex-wrap items-center gap-2',
    navLink: 'inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 shadow-2xs transition-colors hover:bg-slate-50 dark:border-[#2e2e2e] dark:bg-[#141414] dark:text-slate-300 dark:hover:bg-[#242424]',
    refreshButton: 'inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 shadow-2xs transition-colors hover:bg-slate-50 dark:border-[#2e2e2e] dark:bg-[#141414] dark:text-slate-300 dark:hover:bg-[#242424]',
  },
  telemetry: {
    grid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4',
    card: 'rounded-xl border border-slate-200 bg-white p-5 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a] flex flex-col justify-between',
    cardHeader: 'flex items-center justify-between text-slate-500 dark:text-slate-400 mb-2',
    label: 'text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400',
    iconWrapper: 'flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100 text-[#a8071a] dark:bg-slate-800 dark:text-rose-400',
    value: 'text-2xl font-bold tracking-tight text-slate-900 dark:text-white mt-1',
    help: 'text-xs text-slate-500 dark:text-slate-400 mt-1',
  },
  options: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    header: 'mb-5 pb-4 border-b border-slate-100 dark:border-slate-800/80',
    title: 'text-base font-bold text-slate-900 dark:text-white',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400 mt-0.5',
    modeTabs: 'flex flex-wrap gap-2 mb-6',
    modeTab: {
      active: 'inline-flex items-center gap-2 rounded-lg bg-[#a8071a] px-4 py-2.5 text-xs font-bold text-white shadow-xs transition-colors',
      idle: 'inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-4 py-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-100 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800 transition-colors',
    },
    grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 items-start',
    field: 'space-y-1.5',
    fieldLabel: 'text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center justify-between',
    select: 'w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-800 outline-none transition-colors focus:border-[#a8071a] focus:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:focus:border-rose-500',
    formatCardsGrid: 'grid grid-cols-1 sm:grid-cols-2 gap-3',
    formatCard: {
      active: 'relative flex flex-col p-4 rounded-xl border-2 border-[#a8071a] bg-rose-50/40 dark:border-rose-500 dark:bg-rose-950/20 cursor-pointer transition-all shadow-xs',
      idle: 'relative flex flex-col p-4 rounded-xl border border-slate-200 bg-slate-50/60 dark:border-slate-800 dark:bg-slate-900/40 cursor-pointer hover:border-slate-300 dark:hover:border-slate-700 transition-all',
    },
    formatTitle: 'text-xs font-bold text-slate-900 dark:text-white flex items-center gap-2 mb-1',
    formatDesc: 'text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed',
    toggleCard: 'flex items-start gap-3 rounded-lg border border-slate-200 bg-slate-50/70 p-3.5 dark:border-slate-800 dark:bg-slate-900/40',
    checkbox: 'mt-0.5 h-4 w-4 rounded border-slate-300 text-[#a8071a] focus:ring-[#a8071a] dark:border-slate-700 dark:bg-slate-800 dark:checked:bg-[#a8071a]',
    toggleTextBlock: 'space-y-0.5',
    toggleTitle: 'text-xs font-semibold text-slate-800 dark:text-slate-200 select-none cursor-pointer',
    toggleHelp: 'text-[11px] text-slate-500 dark:text-slate-400 leading-normal select-none',
  },
  dateBrowser: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    header: 'flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-5 pb-4 border-b border-slate-100 dark:border-slate-800/80',
    title: 'text-base font-bold text-slate-900 dark:text-white',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400 mt-0.5',
    yearSelectorRow: 'flex items-center gap-2 mb-4',
    yearBtn: {
      active: 'rounded-lg bg-[#a8071a] px-3.5 py-1.5 text-xs font-bold text-white shadow-xs',
      idle: 'rounded-lg border border-slate-200 bg-slate-50 px-3.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-100 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800',
    },
    searchBox: 'relative max-w-xs w-full',
    searchInput: 'w-full rounded-lg border border-slate-200 bg-slate-50 pl-8 pr-3 py-1.5 text-xs text-slate-800 outline-none focus:border-[#a8071a] focus:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200',
    searchIcon: 'absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 text-sm',
    monthsGrid: 'grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3 mb-4',
    monthCard: {
      active: 'p-3 rounded-lg border-2 border-[#a8071a] bg-rose-50/60 text-[#a8071a] dark:border-rose-500 dark:bg-rose-950/30 dark:text-rose-300 text-center font-bold text-xs cursor-pointer shadow-xs',
      available: 'p-3 rounded-lg border border-slate-200 bg-white text-slate-800 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200 text-center font-semibold text-xs cursor-pointer hover:border-slate-400 dark:hover:border-slate-600 transition-colors',
      disabled: 'p-3 rounded-lg border border-slate-100 bg-slate-50/50 text-slate-400 dark:border-slate-800/40 dark:bg-slate-900/20 dark:text-slate-600 text-center text-xs cursor-not-allowed opacity-60',
    },
    daysGrid: 'grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-2.5 max-h-80 overflow-y-auto p-1 border border-slate-200/70 rounded-lg dark:border-slate-800',
    dayChip: {
      active: 'p-3 rounded-lg border-2 border-[#a8071a] bg-rose-50/80 text-[#a8071a] dark:border-rose-500 dark:bg-rose-950/40 dark:text-rose-200 text-left font-bold text-xs cursor-pointer shadow-2xs',
      idle: 'p-3 rounded-lg border border-slate-200 bg-slate-50 text-slate-800 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200 text-left font-medium text-xs cursor-pointer hover:border-[#a8071a]/50 hover:bg-rose-50/20 dark:hover:border-rose-500/30 dark:hover:bg-rose-950/20 transition-all',
    },
    rangesGrid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4',
    rangeCard: {
      active: 'p-4 rounded-xl border-2 border-[#a8071a] bg-rose-50/50 dark:border-rose-500 dark:bg-rose-950/30 cursor-pointer shadow-xs',
      idle: 'p-4 rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900/60 cursor-pointer hover:border-slate-300 dark:hover:border-slate-700 transition-all',
    },
  },
  preview: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    header: 'flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-5 pb-4 border-b border-slate-100 dark:border-slate-800/80',
    title: 'text-base font-bold text-slate-900 dark:text-white',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400 mt-0.5',
    specGrid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6',
    specBox: 'rounded-lg border border-slate-200 bg-slate-50 p-3.5 space-y-1 dark:border-slate-800 dark:bg-slate-900/50',
    specLabel: 'text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400',
    specValue: 'text-xs font-bold text-slate-900 dark:text-white break-words',
    specHelp: 'text-[11px] text-slate-500 dark:text-slate-400',
    milestonesContainer: 'space-y-3 mb-6',
    milestonesTitle: 'text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300',
    milestonesGrid: 'grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2',
    milestoneChip: 'rounded-lg border border-slate-200 bg-slate-50/80 p-2.5 text-center dark:border-slate-800 dark:bg-slate-900/40',
    milestoneCol: 'font-mono text-[10px] font-bold text-[#a8071a] dark:text-rose-400',
    milestoneName: 'text-xs font-semibold text-slate-800 dark:text-slate-200 mt-0.5',
    milestoneField: 'text-[10px] font-mono text-slate-500 dark:text-slate-400 mt-0.5',
    formulasContainer: 'rounded-xl border border-slate-200 bg-slate-50/60 p-4 space-y-3 mb-6 dark:border-slate-800 dark:bg-slate-900/30',
    formulasHeader: 'text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300',
    formulasGrid: 'grid grid-cols-1 sm:grid-cols-2 gap-3',
    formulaItem: 'rounded-lg border border-slate-200 bg-white p-3 space-y-1 dark:border-slate-800 dark:bg-[#1a1a1a]',
    formulaIndicator: 'text-xs font-bold text-slate-900 dark:text-white',
    formulaTarget: 'text-[11px] font-semibold text-[#a8071a] dark:text-rose-400',
    formulaCode: 'font-mono text-[10px] text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800/80 px-2 py-0.5 rounded',
    actionRow: 'flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-100 dark:border-slate-800/80',
    downloadButton: 'w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-lg bg-[#a8071a] px-6 py-3 text-xs font-bold text-white shadow-xs hover:bg-[#8e0616] focus:outline-none focus:ring-2 focus:ring-[#a8071a]/50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors',
  },
  history: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    header: 'flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-4',
    title: 'text-base font-bold text-slate-900 dark:text-white flex items-center gap-2',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400',
    badge: 'rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-300',
    clearButton: 'rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600 transition-colors hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-400 dark:hover:bg-slate-800',
    tableWrapper: 'overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800',
    table: 'w-full text-left text-xs',
    thead: 'border-b border-slate-200 bg-slate-50 font-semibold text-slate-700 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-300',
    th: 'px-4 py-3',
    tbody: 'divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-[#1a1a1a]',
    tr: 'hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition-colors',
    td: 'px-4 py-3 text-slate-800 dark:text-slate-200 align-middle',
    statusBadge: {
      success: 'rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-900',
      failed: 'rounded-full bg-rose-50 px-2.5 py-1 text-[11px] font-semibold text-rose-700 dark:bg-rose-950/40 dark:text-rose-300 border border-rose-200 dark:border-rose-900',
    },
    redownloadBtn: 'inline-flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-2.5 py-1 font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700 transition-colors',
    emptyBox: 'p-8 text-center text-xs font-semibold text-slate-500 dark:text-slate-400',
  },
  guide: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    title: 'text-base font-bold text-slate-900 dark:text-white mb-1 flex items-center gap-2',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400 mb-5',
    grid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
    formatBox: 'rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-2 dark:border-slate-800 dark:bg-slate-900/40',
    formatTitle: 'text-xs font-bold text-slate-900 dark:text-white flex items-center gap-1.5',
    formatDesc: 'text-xs text-slate-600 dark:text-slate-400 leading-relaxed',
  },
  results: {
    banner: 'rounded-xl border border-emerald-200 bg-emerald-50/80 p-5 shadow-xs dark:border-emerald-900/60 dark:bg-emerald-950/20',
    header: 'flex items-start gap-3',
    iconWrapper: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-400',
    content: 'flex-1 space-y-1',
    title: 'text-sm font-bold text-emerald-900 dark:text-emerald-200',
    subtitle: 'text-xs text-emerald-700 dark:text-emerald-300',
    metricsGrid: 'grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4 pt-4 border-t border-emerald-200/80 dark:border-emerald-900/60',
    metricBox: 'space-y-0.5',
    metricLabel: 'text-[10px] font-semibold uppercase tracking-wider text-emerald-800/80 dark:text-emerald-300/80',
    metricVal: 'text-base font-bold text-emerald-950 dark:text-emerald-100',
    actionsRow: 'flex flex-wrap items-center gap-2 mt-4',
    primaryLink: 'inline-flex items-center gap-1.5 rounded-lg bg-emerald-700 px-3.5 py-1.5 text-xs font-semibold text-white shadow-2xs hover:bg-emerald-800 transition-colors',
    secondaryLink: 'inline-flex items-center gap-1.5 rounded-lg border border-emerald-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-emerald-800 hover:bg-emerald-50 dark:border-emerald-800 dark:bg-slate-900 dark:text-emerald-300 dark:hover:bg-emerald-950/30 transition-colors',
  },
} as const;
