/**
 * @fileoverview Text definitions and copy strings for the Analytics dashboard page.
 *
 * All user-facing labels, headings, descriptions, table headers, button text,
 * and empty state messages are centralized here to adhere strictly to the
 * repository's separation of concerns guidelines.
 *
 * @module app/dashboard/pages/analytics/constants/analyticsTexts
 */

export const ANALYTICS_TEXTS = {
  header: {
    title: 'OPD Queue Analytics Dashboard',
    subtitle: 'Advanced forecasting and bottleneck analysis',
    refreshing: 'Refreshing…',
    loading: 'Loading Heart Check Analytics Engine...',
    errorPrefix: 'Error:',
    empty: 'No data received.',
  },
  presets: {
    '90d': 'Last 90 Days',
    '180d': 'Last 6 Months',
    '365d': 'Last Year',
    all: 'All Time',
  },
  export: {
    buttonIdle: 'Export to Excel',
    buttonLoading: 'Exporting...',
    defaultError: 'Export failed — try a different date range.',
  },
  exportModal: {
    title: 'Export Queue Data to Excel',
    subtitle:
      'Select a specific date, calendar month, or all dates to download the official PHC Time and Motion Analysis workbook (.xlsx).',
    closeAria: 'Close export modal',
    modeLabel: 'Export Selection Mode',
    modes: {
      specific: 'Specific Date',
      all: 'All Dates',
      month: 'By Month',
    },
    specificDateLabel: 'Specific Date',
    specificDateInputAria: 'Select specific date for export',
    recordedDatesLabel: 'Or Select from Recorded Dates',
    recordedDatesSelectAria: 'Select from dates with recorded patient data',
    selectRecordedDatePlaceholder: 'Select a recorded date...',
    noRecordedDates: 'No recorded dates available',
    hasRecordsBadge: 'Queue records available for this date',
    noRecordsBadge: 'No queue records found on this date',
    allDatesNotice:
      'All historical queue data across all recorded dates will be compiled into a single multi-sheet Excel workbook.',
    allDatesTargetPeriod: 'All Recorded Dates (All Time)',
    allDatesStructureValue: '1 sheet per calendar day across entire history',
    specificDateStructureValue: '1 sheet for selected date (Manila Time)',
    monthStructureValue: '1 sheet per calendar day in selected month',
    singleDaySuffix: '(Single Day)',
    yearLabel: 'Year',
    monthLabel: 'Month',
    serviceLabel: 'Clinic / Service',
    allServices: 'All Services (OPD)',
    previewTitle: 'Export Specification',
    targetPeriodLabel: 'Target Period:',
    formatLabel: 'File Format:',
    formatValue: 'Microsoft Excel (.xlsx)',
    structureLabel: 'Structure:',
    structureValue: '1 sheet per calendar day (Manila Time)',
    cancelButton: 'Cancel',
    confirmButton: 'Export to Excel',
    confirmLoading: 'Generating Workbook...',
    downloadSuccess: 'Export generated successfully. Starting download...',
    defaultError: 'Export failed — please check if patient records exist for this period.',
    noDataError: 'No patient records found for the selected date or period.',
    loadingDates: 'Checking available dates...',
    noAvailableDates: 'No patient records found for export.',
    noMonthsForYear: 'No records available for the selected year.',
    prevYearAria: 'Previous available year',
    nextYearAria: 'Next available year',
    months: [
      { name: 'January', short: 'Jan', value: 1 },
      { name: 'February', short: 'Feb', value: 2 },
      { name: 'March', short: 'Mar', value: 3 },
      { name: 'April', short: 'Apr', value: 4 },
      { name: 'May', short: 'May', value: 5 },
      { name: 'June', short: 'Jun', value: 6 },
      { name: 'July', short: 'Jul', value: 7 },
      { name: 'August', short: 'Aug', value: 8 },
      { name: 'September', short: 'Sep', value: 9 },
      { name: 'October', short: 'Oct', value: 10 },
      { name: 'November', short: 'Nov', value: 11 },
      { name: 'December', short: 'Dec', value: 12 },
    ] as const,
    services: [
      { label: 'All Services (OPD)', value: 'all' },
      { label: 'Consultation', value: 'Consultation' },
      { label: 'ECG', value: 'ECG' },
      { label: 'Warfarin Clinic', value: 'Warfarin Clinic' },
      { label: 'OPD Card', value: 'OPD Card' },
      { label: 'OPD Screening', value: 'OPD Screening' },
      { label: 'OPD Reschedule', value: 'OPD Reschedule' },
      { label: 'Refill Prescription', value: 'Refill Prescription' },
      { label: 'Benzathine', value: 'Benzathine' },
    ] as const,
  },
  metrics: {
    systemStatus: {
      label: 'System Status',
      bottleneckPrefix: 'Bottleneck:',
      noneLabel: 'None',
    },
    avgPatientTime: {
      label: 'Avg. Total Patient Time',
      subtitle: 'Queuing to Doctor Completed',
    },
    nextDayForecast: {
      label: 'Next-Day Forecast',
      unit: 'patients',
      subtitlePrefix: 'For',
      viaPrefix: 'via',
      defaultDate: 'next recorded day',
    },
    recommendedStaff: {
      label: 'Recommended Staff',
      unit: 'Doctors',
      subtitle: 'Target staffing for predicted load',
    },
  },
  bottleneckTable: {
    title: 'Queue Stage Breakdown',
    subtitle:
      'Where patients spend the most time, kiosk through carryout — with severity and reasoning per stage.',
    empty: 'No stage data available for the selected range.',
    headers: {
      stage: 'Stage',
      avgTime: 'Avg. Time',
      patients: 'Patients',
      level: 'Level',
      reason: 'Reason',
    },
    levels: {
      Normal: 'Normal',
      Elevated: 'Elevated',
      Overwhelmed: 'Overwhelmed',
      'No Data': 'No Data',
    },
  },
  volumeCharts: {
    dailyVolumeTitle: 'Daily Patient Volume & Moving Average',
    dailyVolumeSubtitle: 'Raw daily counts with a 7-day smoothed trend line (click any date or bar to drill down)',
    hourlyPatternTitle: 'Hourly Arrival Distribution',
    hourlyPatternSubtitle: 'Average intake across clinic operating hours',
    hourlyDrilldownSubtitle: 'Actual patient intake for selected date',
    stageWaitTitle: 'Stage-by-Stage Wait Time Trends',
    stageWaitSubtitle: 'Average minutes elapsed per operational step (click any date to drill down)',
    clickHint: 'Tip: Click on any date or bar in the Daily Volume or Stage Wait Time charts to inspect that day\'s hourly distribution and bottleneck breakdown.',
    chartClickTooltip: 'Click to drill down into',
    resetButton: 'Reset to Overall Pattern',
    activeBadge: 'Drill-Down Active',
    series: {
      dailyPatients: 'Daily Patients',
      movingAvg: '7-Day Moving Avg',
      avgPatients: 'Avg Patients',
      selectedDayPatients: 'Selected Day Intake',
      rangeAverage: 'Overall Average',
    },
  },
  drilldown: {
    title: 'Daily Drill-Down Analysis',
    subtitle: 'Granular hourly patient arrivals, queue stage dwell times, and bottleneck breakdown for',
    activeBadge: 'Drill-Down Active',
    resetButton: 'Reset to Overall Range',
    clearAria: 'Clear selected date drilldown',
    patientsSeen: 'Patients Seen',
    patientsUnit: 'patients',
    avgTotalTime: 'Avg. Total Patient Time',
    avgTotalTimeSub: 'Queuing to Doctor Completed',
    peakHour: 'Peak Arrival Hour',
    peakHourSub: 'Highest patient intake window',
    primaryBottleneck: 'Primary Bottleneck',
    primaryBottleneckSub: 'Highest dwell time step',
    systemStatus: 'System Status',
    bottleneckSectionTitle: 'Daily Queue Stage Breakdown',
    bottleneckSectionSubtitle: 'Where patients spent the most time on this date, with severity and clinical reasoning',
    hourlySectionTitle: 'Hourly Arrival Distribution Comparison',
    hourlySectionSubtitle: 'Comparing patient arrivals on this date against the overall range average',
    loading: 'Loading granular drill-down metrics for',
    errorPrefix: 'Failed to load drill-down data:',
    retryButton: 'Retry',
    emptyForDate: 'No granular queue records found on this date.',
    noData: 'No Data',
    headers: {
      stage: 'Stage',
      avgTime: 'Avg. Time',
      patients: 'Patients',
      level: 'Level',
      reason: 'Reason',
    },
  },
  compliance: {
    title: 'PHC Waiting Time Compliance',
    subtitle: 'Department standards and threshold performance',
    patientsSeenLabel: 'Patients Seen',
    operatingHoursLabel: 'OPD Operating Hours',
    operatingHoursUnit: 'hrs/day',
    avgTotalWaitLabel: "Avg. Patient's Total Waiting Time",
    thresholdTableTitle: 'Compliance Breakdown Against Department Standard',
    headers: {
      stage: 'Queue Stage',
      standard: 'PHC Standard',
      withinStandard: 'Within Standard (≤)',
      exceededStandard: 'Exceeded Standard (>)',
      complianceRate: 'Compliance Rate',
    },
    stages: {
      waitingTime: 'Queue to Triage & Registration',
      evaluate: 'Initial Nursing Evaluation',
      examineTreat: 'Physician Examination & Treatment',
      carryout: 'Prescription Carryout & Disposition',
    },
  },
  forecasts: {
    lr: {
      title: 'Linear Regression Forecast',
      subtitle: 'Trend prediction based on historical patient registrations',
      r2Label: 'R² =',
      nextDayLabel: 'Next Day =',
      patientsUnit: 'patients',
    },
    arima: {
      title: 'ARIMA Forecast',
      subtitle: 'Autoregressive integrated moving average predictive model',
      aicPrefix: 'AIC:',
      modelTag: 'ARIMA (1,1,1)',
      forecastForPrefix: 'Forecast for',
      patientsUnit: 'patients',
      residualVariance: 'Residual Variance (σ²):',
      forecastDateLabel: 'Forecast Date',
    },
    comparison: {
      title: 'Algorithm Comparison',
      headers: {
        algorithm: 'Algorithm',
        mae: 'MAE',
        rmse: 'RMSE',
      },
      arimaLabel: 'ARIMA',
      bestIndicator: '✓',
    },
  },
} as const;
