/**
 * @fileoverview Style tokens and Tailwind class definitions for the Admin Dashboard Import Data module.
 *
 * Implements high-contrast solid surfaces, enterprise clinical borders, responsive
 * layouts, and interactive dropzone visual states conforming strictly to AGENTS.md.
 *
 * @module app/dashboard/pages/import/constants/importStyles
 */

export const IMPORT_STYLES = {
  page: 'space-y-6 pb-12',
  header: {
    root: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    topRow: 'flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between',
    titleBlock: 'space-y-1',
    breadcrumb: 'text-xs font-semibold tracking-wide uppercase text-slate-500 dark:text-slate-400',
    title: 'text-2xl font-bold tracking-tight text-slate-900 dark:text-white',
    subtitle: 'text-sm text-slate-600 dark:text-slate-400 max-w-3xl leading-relaxed',
    backLink: 'inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-700 shadow-2xs transition-colors hover:bg-slate-50 dark:border-[#2e2e2e] dark:bg-[#141414] dark:text-slate-300 dark:hover:bg-[#242424]',
  },
  dropzone: {
    wrapper: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    area: {
      idle: 'relative flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50/50 p-10 text-center transition-all duration-150 hover:border-[#a8071a]/50 hover:bg-rose-50/20 dark:border-slate-700 dark:bg-slate-900/30 dark:hover:border-rose-500/40 dark:hover:bg-rose-950/20 cursor-pointer',
      active: 'relative flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#a8071a] bg-rose-50/80 p-10 text-center transition-all duration-150 dark:border-rose-500 dark:bg-rose-950/40 phc-dropzone cursor-pointer scale-[1.005] shadow-xs',
    },
    iconWrapper: 'mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-rose-100 text-[#a8071a] transition-transform dark:bg-rose-950/50 dark:text-rose-400',
    icon: 'text-3xl',
    title: 'text-base font-bold text-slate-900 dark:text-white mb-1',
    subtitle: 'text-sm text-slate-600 dark:text-slate-400 mb-4',
    formatPills: 'flex flex-wrap items-center justify-center gap-2 text-xs text-slate-500 dark:text-slate-400 mt-2',
    pill: 'rounded-md bg-slate-100 px-2.5 py-1 font-medium text-slate-700 dark:bg-slate-800 dark:text-slate-300 border border-slate-200/80 dark:border-slate-700',
    browseButton: 'inline-flex items-center gap-2 rounded-lg bg-[#a8071a] px-4 py-2 text-xs font-semibold text-white shadow-xs transition-colors hover:bg-[#8e0616] focus:outline-none focus:ring-2 focus:ring-[#a8071a]/50',
  },
  options: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    header: 'mb-5 pb-4 border-b border-slate-100 dark:border-slate-800/80',
    title: 'text-sm font-bold text-slate-900 dark:text-white',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400 mt-0.5',
    grid: 'grid grid-cols-1 md:grid-cols-3 gap-6 items-start',
    field: 'space-y-1.5',
    label: 'text-xs font-semibold text-slate-700 dark:text-slate-300 flex items-center justify-between',
    select: 'w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-800 outline-none transition-colors focus:border-[#a8071a] focus:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:focus:border-rose-500',
    input: 'w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-medium text-slate-800 outline-none transition-colors focus:border-[#a8071a] focus:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:focus:border-rose-500',
    toggleCard: 'flex items-start gap-3 rounded-lg border border-slate-200 bg-slate-50/70 p-3.5 dark:border-slate-800 dark:bg-slate-900/40',
    checkbox: 'mt-0.5 h-4 w-4 rounded border-slate-300 text-[#a8071a] focus:ring-[#a8071a] dark:border-slate-700 dark:bg-slate-800 dark:checked:bg-[#a8071a]',
    toggleTextBlock: 'space-y-0.5',
    toggleTitle: 'text-xs font-semibold text-slate-800 dark:text-slate-200 select-none cursor-pointer',
    toggleHelp: 'text-[11px] text-slate-500 dark:text-slate-400 leading-normal select-none',
  },
  stagedFiles: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    header: 'flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-4',
    titleBlock: 'space-y-0.5',
    title: 'text-base font-bold text-slate-900 dark:text-white flex items-center gap-2',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400',
    badge: 'rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-300',
    actionsRow: 'flex items-center gap-2',
    clearButton: 'rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600 transition-colors hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-400 dark:hover:bg-slate-800',
    importAllButton: 'inline-flex items-center gap-1.5 rounded-lg bg-[#a8071a] px-4 py-1.5 text-xs font-semibold text-white shadow-xs transition-colors hover:bg-[#8e0616] focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed',
    tableWrapper: 'overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800',
    table: 'w-full text-left text-xs',
    thead: 'border-b border-slate-200 bg-slate-50 font-semibold text-slate-700 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-300',
    th: 'px-4 py-3',
    tbody: 'divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-[#1a1a1a]',
    tr: 'hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition-colors',
    td: 'px-4 py-3 text-slate-800 dark:text-slate-200 align-middle',
    fileName: 'font-semibold text-slate-900 dark:text-white flex items-center gap-2',
    fileIcon: 'text-base text-[#a8071a] dark:text-rose-400',
    typePill: 'rounded px-2 py-0.5 font-mono text-[11px] font-medium uppercase',
    statusBadge: {
      pending: 'rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-300',
      inspecting: 'rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-semibold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300 border border-blue-200 dark:border-blue-900',
      readyToCommit: 'rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-semibold text-amber-700 dark:bg-amber-950/40 dark:text-amber-300 border border-amber-200 dark:border-amber-900',
      importing: 'rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-semibold text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-900 animate-pulse',
      completed: 'rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-900',
      error: 'rounded-full bg-rose-50 px-2.5 py-1 text-[11px] font-semibold text-rose-700 dark:bg-rose-950/40 dark:text-rose-300 border border-rose-200 dark:border-rose-900',
    },
    actionButtonsRow: 'flex items-center gap-1.5',
    inspectButton: 'rounded-md border border-slate-200 bg-white px-2.5 py-1 font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700 transition-colors',
    importSingleButton: 'rounded-md bg-[#a8071a] px-2.5 py-1 font-semibold text-white hover:bg-[#8e0616] transition-colors',
    removeButton: 'rounded-md p-1 text-slate-400 hover:bg-slate-100 hover:text-rose-600 dark:hover:bg-slate-800 dark:hover:text-rose-400 transition-colors',
    emptyBox: 'p-8 text-center text-xs font-semibold text-slate-500 dark:text-slate-400',
  },
  modal: {
    backdrop: 'fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-xs',
    container: 'relative flex max-h-[90vh] w-full max-w-4xl flex-col rounded-2xl border border-slate-200 bg-white shadow-xl dark:border-[#2e2e2e] dark:bg-[#1a1a1a] overflow-hidden',
    header: 'flex items-center justify-between border-b border-slate-200 p-5 dark:border-slate-800',
    titleBlock: 'space-y-0.5',
    title: 'text-base font-bold text-slate-900 dark:text-white',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400',
    closeButton: 'rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800 dark:hover:text-slate-200',
    body: 'overflow-y-auto p-5 space-y-5 flex-1',
    kpiGrid: 'grid grid-cols-2 sm:grid-cols-5 gap-3',
    kpiCard: 'rounded-xl border border-slate-200 bg-slate-50 p-3 text-center dark:border-slate-800 dark:bg-slate-900/60',
    kpiLabel: 'text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider',
    kpiValue: 'text-lg font-bold text-slate-900 dark:text-white mt-0.5',
    tableTitle: 'text-xs font-bold uppercase tracking-wider text-slate-700 dark:text-slate-300 mb-2',
    tableWrapper: 'overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800 max-h-64',
    footer: 'flex items-center justify-end gap-2 border-t border-slate-200 p-4 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/30',
    cancelBtn: 'rounded-lg border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700',
    confirmBtn: 'inline-flex items-center gap-1.5 rounded-lg bg-[#a8071a] px-4 py-2 text-xs font-semibold text-white hover:bg-[#8e0616] transition-colors',
  },
  results: {
    banner: 'rounded-xl border border-emerald-200 bg-emerald-50/80 p-5 shadow-xs dark:border-emerald-900/60 dark:bg-emerald-950/20',
    header: 'flex items-start gap-3',
    iconWrapper: 'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-400',
    content: 'flex-1 space-y-1',
    title: 'text-sm font-bold text-emerald-900 dark:text-emerald-200',
    subtitle: 'text-xs text-emerald-700 dark:text-emerald-300',
    metricsGrid: 'grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-emerald-200/80 dark:border-emerald-900/60',
    metricBox: 'space-y-0.5',
    metricLabel: 'text-[10px] font-semibold uppercase tracking-wider text-emerald-800/80 dark:text-emerald-300/80',
    metricVal: 'text-base font-bold text-emerald-950 dark:text-emerald-100',
    actionsRow: 'flex flex-wrap items-center gap-2 mt-4',
    primaryLink: 'inline-flex items-center gap-1.5 rounded-lg bg-emerald-700 px-3.5 py-1.5 text-xs font-semibold text-white shadow-2xs hover:bg-emerald-800 transition-colors',
    secondaryLink: 'inline-flex items-center gap-1.5 rounded-lg border border-emerald-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-emerald-800 hover:bg-emerald-50 dark:border-emerald-800 dark:bg-slate-900 dark:text-emerald-300 dark:hover:bg-emerald-950/30 transition-colors',
  },
  guide: {
    card: 'rounded-xl border border-slate-200 bg-white p-6 shadow-xs dark:border-[#2e2e2e] dark:bg-[#1a1a1a]',
    title: 'text-sm font-bold text-slate-900 dark:text-white mb-1 flex items-center gap-2',
    subtitle: 'text-xs text-slate-500 dark:text-slate-400 mb-4',
    grid: 'grid grid-cols-1 md:grid-cols-2 gap-4',
    formatBox: 'rounded-lg border border-slate-200 bg-slate-50 p-4 space-y-2 dark:border-slate-800 dark:bg-slate-900/40',
    formatTitle: 'text-xs font-bold text-slate-900 dark:text-white flex items-center gap-1.5',
    formatDesc: 'text-xs text-slate-600 dark:text-slate-400 leading-relaxed',
    columnsTag: 'text-[11px] font-semibold text-slate-700 dark:text-slate-300 bg-white dark:bg-slate-800 p-2 rounded border border-slate-200 dark:border-slate-700',
  },
} as const;
