//! DO NOT DELETE THIS FILE! This is the root layout for the application.
//! This will serve as the instruction before using kiosk

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { tiltWarp, Baloo } from "@/fonts/fonts"; // 👈 add this (adjust path if needed)
import { LanguageProvider } from "@/app/LanguageContext";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${tiltWarp.variable} ${Baloo.variable}`}> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}