/**
 * @fileoverview Text definitions and copy strings for the Cubicles dashboard page.
 *
 * All user-facing labels, headings, descriptions, status badges, and empty messages
 * are centralized here adhering to the repository's separation of concerns guidelines.
 *
 * @module app/dashboard/pages/cubicles/constants/cubiclesTexts
 */

export const CUBICLES_TEXTS = {
  header: {
    title: 'Live Cubicle Dashboard',
    subtitle: 'Real-time status of examination cubicles and active consultations',
    lastUpdatedPrefix: 'Last updated:',
    loading: 'Loading cubicle data',
    errorPrefix: 'Error loading cubicles:',
  },
  metrics: {
    total: {
      label: 'Total Cubicles',
      subtitle: 'Configured examination units',
    },
    available: {
      label: 'Available',
      subtitle: 'Ready for next patient',
    },
    occupied: {
      label: 'Occupied',
      subtitle: 'Consultation in progress',
    },
    unavailable: {
      label: 'Unavailable',
      subtitle: 'Maintenance or cleaning',
    },
  },
  grid: {
    title: 'Cubicle Status',
    subtitle: 'Physical exam rooms and real-time patient occupancy',
    emptyTitle: 'No cubicles configured in the system.',
    emptySubtitle: 'Contact system administrator to configure clinical cubicles.',
  },
  card: {
    patientPrefix: 'Patient:',
    servicePrefix: 'Service:',
    sincePrefix: 'Since:',
    estEndPrefix: 'Est. end:',
    lessThanMinute: '<1m',
  },
  legend: {
    title: 'Status Legend',
    subtitle: 'Operational state definitions for clinical rooms',
    available: 'Available',
    occupied: 'Occupied',
    maintenance: 'Maintenance',
    cleaning: 'Cleaning',
  },
  heatmap: {
    title: 'Operational Throughput & Idle Interval Heatmap',
    subtitle:
      'Visualizing patient processing speed and cubicle downtime across the operational day',
    modes: {
      speed: 'Processing Speed',
      idle: 'Idle Intervals',
      dual: 'Dual Overview',
    },
    date: {
      label: 'Operational Day:',
      today: 'Today (Live)',
      allAvailable: 'Available Dates',
      refresh: 'Refresh Heatmap',
      liveIndicator: 'Live Sync',
      operatingHoursLabel: 'Clinic Schedule: 07:00 - 17:00',
    },
    kpis: {
      throughput: {
        label: 'Daily Throughput',
        subtitle: 'Consultations completed',
      },
      avgSpeed: {
        label: 'Avg Processing Speed',
        subtitle: 'Minutes per patient',
      },
      avgIdle: {
        label: 'Avg Idle Downtime',
        subtitle: 'Room gap between patients',
      },
      utilization: {
        label: 'Room Utilization Rate',
        subtitle: 'Active examination occupancy',
      },
    },
    table: {
      cubicleCol: 'Examination Unit',
      summaryCol: 'Day Summary',
      hourlyTotalRow: 'Hourly Facility Aggregate',
      ptsUnit: 'pts',
      ptUnit: 'pt',
      minsUnit: 'm',
      idleUnit: 'idle',
      activeUnit: 'active',
      upcomingSlot: 'Upcoming',
      noPatients: 'Dormant',
      assignedDoctorPrefix: 'Dr.',
      unassignedDoctor: 'No physician assigned',
      totalServedPrefix: 'Served:',
      avgSpeedPrefix: 'Avg:',
      utilizationPrefix: 'Util:',
      clickForDetails: 'Click cell to inspect consultations',
    },
    speedRatings: {
      fast: 'Fast (<15m)',
      optimal: 'Optimal (15-25m)',
      moderate: 'Moderate (25-35m)',
      slow: 'Extended (>35m)',
      inactive: 'Inactive (0 pts)',
    },
    idleRatings: {
      continuous: 'Continuous (<10m idle)',
      lowIdle: 'Low Idle (10-25m)',
      moderateIdle: 'Moderate Idle (25-40m)',
      highIdle: 'High Idle (40-55m)',
      dormant: 'Dormant (60m idle)',
    },
    legend: {
      title: 'Heatmap Interpretation Guide',
      speedTitle: 'Patient Processing Speed Scale',
      idleTitle: 'Cubicle Idle Downtime Scale',
      targetBenchmark: 'Clinical Target: 15 to 20 minutes per consultation',
    },
    modal: {
      title: 'Cubicle Hourly Interval Details',
      close: 'Close',
      slotDetails: 'Time Slot:',
      physician: 'Physician:',
      patientsTreated: 'Patients Consulted',
      processingSpeed: 'Processing Speed',
      idleDuration: 'Idle Downtime',
      utilization: 'Occupancy Rate',
      patientLog: 'Consultation Log in this Window',
      noPatientsInSlot:
        'No patient consultations were recorded in this cubicle during this hourly interval.',
      durationLabel: 'Duration:',
      consultRange: 'Window:',
      serviceLabel: 'Service:',
      statusLabel: 'Status:',
    },
    empty: {
      title: 'No Operational Records for Selected Day',
      subtitle:
        'No consultation starts or patient assignments were recorded in the database for this date.',
      selectAnotherDate: 'Select another operational date from the dropdown menu above.',
    },
  },
  flowchart: {
    title: 'Outpatient Cubicle Pipeline Flowchart',
    subtitle:
      'Real-time stage-by-stage progression, active examination stations, and idle turnaround intervals',
    kpis: {
      inPipeline: 'Active Pipeline',
      inPipelineSub: 'Patients in transit & exam',
      meanSpeed: 'Mean Processing Speed',
      meanSpeedSub: 'Target: 15-20m / pt',
      meanIdle: 'Avg Idle Downtime',
      meanIdleSub: 'Room turnover gap',
      utilization: 'Cubicle Utilization',
      utilizationSub: 'Active exam occupancy',
      liveSync: 'Live Synchronization',
    },
    stages: {
      waiting: {
        title: '1. Kiosk',
        subtitle: 'Self-service check-in',
        metric: 'Mean Wait Time',
        empty: 'No waiting patients',
      },
      dispatch: {
        title: '2. Registration',
        subtitle: 'Verification counters',
        metric: 'Transit Grace',
        empty: 'No pending registration',
      },
      examination: {
        title: '3. Nurse',
        subtitle: 'Clinical service stations',
        metric: 'Active Rooms',
        empty: 'No active consultations',
      },
      carryout: {
        title: '4. Carryout',
        subtitle: 'Post-consultation instructions',
        metric: 'Mean Carryout',
        empty: 'No patients in carryout',
      },
      completed: {
        title: '5. Finished',
        subtitle: 'Completed & discharged',
        metric: 'Today Served',
        empty: 'No completed records today',
      },
    },
    transitions: {
      t1: 'Proceed to Registration',
      t2: 'Assign to Nurse',
      t3: 'Proceed to Carryout',
      t4: 'Completed',
      r1: 'Route 1: Kiosk to Registration',
      r2: 'Route 2: Registration to Nurse',
      r3: 'Route 3: Nurse to Carryout',
      r4: 'Route 4: Carryout to Finished',
      activeRoute: 'Active Route',
      queueBuffer: 'Queue Buffer',
      stationReady: 'Buffer Idle / Ready',
      overdueAlert: 'Overdue Alert',
      stalledAlert: 'Stalled Alert',
      stagePrefix: 'Stage',
      moreInQueue: 'more in queue',
      itemsInTransit: 'items in transit',
      noItemsOnRoute: 'Route Idle',
      clickToInspectDot: 'Click to inspect queue item',
    },
    hub: {
      title: 'Clinical Examination Stations Telemetry',
      subtitle:
        'Live consultation timers, physician assignments, speed evaluations, and idle intervals per cubicle',
      elapsed: 'Elapsed:',
      estRemaining: 'Est. end:',
      idleGap: 'Idle gap:',
      speedLabel: 'Speed:',
      doctor: 'Doctor:',
      patient: 'Patient:',
      service: 'Service:',
      todayConsults: 'Today consults:',
      todayAvg: 'Day avg:',
      ready: 'Ready for next patient',
      stalledWarning: 'Extended consultation (>35m)',
      clickToInspect: 'Click to inspect room history',
    },
    telemetry: {
      title: 'Cubicle Turnaround & Idle Downtime Telemetry',
      subtitle:
        'Monitors inter-patient room turnaround against clinical standard benchmark (5-10 minutes)',
      benchmark: 'Benchmark: <10m room turnover',
      continuous: 'Continuous Flow',
      lowIdle: 'Turnaround Buffer',
      moderateIdle: 'Moderate Idle',
      highIdle: 'High Downtime',
      turnaroundTime: 'Turnaround gap:',
      activeConsult: 'Exam in progress',
    },
    modal: {
      patientTitle: 'Patient Journey Stage Details',
      cubicleTitle: 'Cubicle Station Telemetry',
      patientNum: 'Ticket:',
      service: 'Service:',
      stage: 'Current Stage:',
      cubicle: 'Room:',
      doctor: 'Physician:',
      enteredAt: 'Stage Entered:',
      elapsed: 'Time in Stage:',
      consultStart: 'Doctor Seen:',
      consultEnd: 'Doctor Completed:',
      close: 'Close',
    },
    map: {
      title: 'Interactive Outpatient Stage Pipeline Map',
      subtitle:
        'Click any stage node or branching cubicle station to inspect patient flow, timers, and idle intervals',
      branchingTitle: 'Stage 3 Nurse Clinical Service Stations',
      branchingSubtitle:
        'Real-time room occupancy, physician roster, active consultation speed, and turnaround idle gaps',
      branchStem: 'Stage 3 Branch: Nurse Stations',
      filterAll: 'All Stages',
      filterWaiting: '1. Kiosk',
      filterDispatch: '2. Registration',
      filterExam: '3. Nurse',
      filterCarryout: '4. Carryout',
      filterCompleted: '5. Finished',
      zoomHint: 'Interactive Stage Map: Click any node to highlight pathway',
      viewAllStages: 'View All Stages',
      inspectingStage: 'Inspecting Stage Flow',
      noPatientsInStage: 'No active patients currently in this stage.',
      inspectTicketHint: 'Click ticket to inspect clinical history and timers',
      clearFilter: 'Reset Stage Filter',
      showingTickets: 'active tickets progressing in this phase',
    },
    processGraph: {
      title: 'Outpatient Queue Process Graph',
      subtitle:
        'Clean minimal orthogonal process graph tracking queue items across branching consultation paths',
      waitingNode: 'Kiosk',
      waitingDesc: 'Self-service check-in',
      dispatchNode: 'Registration',
      dispatchDesc: 'Verification counters',
      stage3Title: '3. Nurse',
      stage3Subtitle: 'Clinical service stations',
      carryoutNode: 'Carryout',
      carryoutDesc: 'Post-consultation instructions',
      completedNode: 'Finished',
      completedDesc: 'Completed & discharged',
      servicesCountSuffix: 'Services',
      activeProcessing: 'Processing',
      idleStation: 'Ready',
      stalledStation: 'Bottleneck',
      clickToInspect: 'Click stage to inspect details',
      liveSync: 'Live Queue Synchronized',
      itemsHeading: 'Items in transit / buffer',
      inTransit: 'In Transit',
      routingTo: 'Routing to',
      processingAt: 'Processing at',
      completedState: 'Completed',
      simulateItemBtn: 'Dispatch Next Item',
      simulateDayBtn: 'Simulate Day Flow',
      stopSimulateBtn: 'Stop Simulation',
      simulatingDayLabel: 'Replaying Day Traffic',
      liveProcessActive: 'Live queue process in progress',
      liveModeBadge: 'Live Mode',
      simulationModeBadge: 'Day Replay Mode',
      activeItemsBadge: 'Active Pipeline Items',
      noActivePatientsOnRoute: 'No moving queue items (idle route)',
      superadminServicesNotice: 'Synchronized with Superadmin Services',
      filterByService: 'Service Flow:',
      groupAll: 'All Stages',
      groupOpd: 'OPD Consultation',
      groupWarfarin: 'Warfarin Clinic',
      groupSpecialized: 'Specialized Services',
      groupOpdSubtitle: 'Adult & general cardiology rooms',
      groupWarfarinSubtitle: 'Anticoagulation management',
      groupSpecializedSubtitle: 'Pedia, ECG, & specialty clinics',
      // Dedicated individual titles and subtitles for all clinical services
      serviceConsultationTitle: 'Consultation',
      serviceConsultationSubtitle: 'Cardiology physician examination rooms',
      serviceScreeningTitle: 'OPD Screening',
      serviceScreeningSubtitle: 'Triage and clinical vital signs assessment',
      serviceWarfarinTitle: 'Warfarin Clinic',
      serviceWarfarinSubtitle: 'Anticoagulation therapy and INR monitoring',
      serviceOpdCardTitle: 'OPD Card',
      serviceOpdCardSubtitle: 'Hospital card issuance and patient records',
      serviceEcgTitle: 'ECG Station',
      serviceEcgSubtitle: 'Electrocardiogram testing and rhythm tracings',
      serviceRefillTitle: 'Refill Prescription',
      serviceRefillSubtitle: 'Fast-track medication renewal and pharmacy review',
      serviceBenzathineTitle: 'Benzathine Clinic',
      serviceBenzathineSubtitle: 'Prophylactic penicillin injection therapy',
      serviceRescheduleTitle: 'OPD Reschedule',
      serviceRescheduleSubtitle: 'Follow-up appointment coordination and rescheduling',
      // High-capacity room and search controls
      searchPlaceholder: 'Search cubicle, room, doctor, or patient ticket',
      searchLabel: 'Search',
      clearSearch: 'Clear search',
      expandAll: 'Expand All',
      collapseAll: 'Collapse Inactive',
      collapseBlock: 'Collapse block',
      expandBlock: 'Expand block',
      allServices: 'All Services',
      allRoomsFilter: 'All Rooms',
      roomPrefix: 'Room',
      roomsCountSuffix: 'rooms',
      cubicleCountSuffix: 'cubicles',
      moreRoomsHint: 'more rooms available',
      activeConsults: 'In Consult',
      availableCount: 'Available',
      totalRooms: 'Rooms',
      inspectStageBtn: 'Inspect Hub',
      noMatchingCubicles: 'No cubicles match your active search filter',
      modal: {
        titlePrefix: 'Stage Details:',
        queueHeading: 'Queued Patients in Stage',
        emptyQueue: 'No queue items currently in this stage.',
        activeItemHeading: 'Currently Processing Patient',
        telemetryHeading: 'Stage Metrics & Telemetry',
        totalServed: 'Total Handled Today:',
        avgDuration: 'Average Handling Time:',
        closeBtn: 'Close Stage Inspector',
        assignedDoctor: 'Attending Physician:',
        statusLabel: 'Stage Status:',
        elapsedLabel: 'Elapsed Processing:',
      },
    },
  },
} as const;



